apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - order_deployment.yaml
  - order_service.yaml

#génération d'une configmap managé par Kustomize à partir d'application.yaml
configMapGenerator:
  - name: order-config #base du nom de la CM générée
    files:
      - application.yaml
    options:
      labels:
        app: order-service